spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost/hospital
    password: 9676411217
   
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: vasamsettisameerraja@gmail.com
    password: lczb kqzk qwcz ncuk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  file:
    name: logs/hospital-app.log
  level:
    root: INFO
    